"""empty message

Revision ID: c277e67187f1
Revises: 59af0df92f2d
Create Date: 2023-06-02 15:40:22.547778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c277e67187f1'
down_revision = '59af0df92f2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=80), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
